### PR TITLE
Reformatted contributions chapter.

### PR DESCRIPTION
**Pull request by r-jsv**
I reformatted the contributions chapter with the following changes:

* Introduces tables instead of lists
* Introduces fun symbols ( ✅  ❄️  ❌  ❓ )
* ~~Language/Typo/Link fixes~~ -> Documentation fixes
* Re-ordered to preserve alphabetic header order

What do you think?

### CODE REVIEW

**Review by TimvdLippe — COMMENTED** [review]
Instead of tables or list, I would like to see a coherent story. E.g. a story just like our chapters. That is a lot more pleasant to read and gives real insight in what we did in the course

**Comment by r-jsv** [comment]
> Instead of tables or list, I would like to see a coherent story. E.g. a story just like our chapters. That is a lot more pleasant to read and gives real insight in what we did in the course

I doubt people have time to do this 😁

**Comment by TimvdLippe** [comment]
Well, for those that do we can create a nice chapter. The chapter is optional and completely voluntary.

**Review by sandervdo — CHANGES_REQUESTED** [review]
The idea is to have a readable chapter, so in the narrative form. So the tables I do not agree with. It's a bonus assignment, so people that do not have the time will simply not participate. 😄

**Comment by r-jsv** [comment]
> Well, for those that do we can create a nice chapter. The chapter is optional and completely voluntary.

> The idea is to have a readable chapter, so in the narrative form. So the tables I do not agree with. It's a bonus assignment, so people that do not have the time will simply not participate. 

In my opinion getting more teams to participate in the contributions chapter is more desirable than making it a narrative chapter. Furthermore, I think it is more powerful to list the pull requests in a table with some nice ✅-emojis  to symbolise that they were merged, rather than baking that into a block of text. I think for the reader it is more impressive to se a lot of merged PR's in a structured tables, and that a long text chapter wouldn't give that effect.

Consider the difference between our [graphical representation](https://github.com/delftswa2017/team-closure-compiler/blob/master/contributions_summary.png) of our contributions and our [text-based representation](https://github.com/delftswa2017/team-closure-compiler/blob/master/contributions.md). In my opinion the graphical one gives a much better impression to the reader.

**Comment by LiamClark** [comment]
+1 for stories

**Comment by sandervdo** [comment]
With a story you can guide the user through your information, which is useful when you have many things to describe. We want to show that this course/book is a collaborative approach, having a joint chapter emphasises this I think. 😄 

I do like the addition of emoji's btw. I think they would fit nice inline as wel like: (#1 ✅ ), but I'll leave that up to you if/how you want to implement this.

**Pull request closed without merging**
