### PR TITLE
Added team JUnit 5's  chapter

### PR DESCRIPTION
**Pull request by jadeleeuw**
Team JUnit 5's DESOSA2017 entry.

### CODE REVIEW

**Comment by LiamClark** [comment]
HELL YEA!

**Review by sandervdo — APPROVED** [review]
As per feedback in your private repository your chapter can be included in the book. You are free to make more improvements before having it merged. Please indicate whether you want to include or exclude your chapter in the book. 😄

**Review by sandervdo — CHANGES_REQUESTED** [review]
Oh, whoops. Please rename `team-junit5` to `junit5`. :wink:

**Comment by joined** [comment]
Awesome work guys, congrats! While reading your chapter I have spotted some typos here and there, I'll post them here so you can fix them before submitting it :)

- Line 9 and following: java -> Java
- Line 47: strife -> strive
- Line 72, 74, 78, 79: Indigogo -> Indiegogo
- Line 73: extend -> extent
- Line 97: lions -> lion's
- Line 145: are teachers -> is teachers
- Line 146: familiarize -> familiarise
- Line 192: standardized -> standardised
- Line 195: visualized -> visualised
- Line 201: Visualization -> Visualisation
- Line 216: visualize -> visualise
- Line 238: is required -> are required
- Line 263: backward -> backwards
- Line 267: a architectural -> an architectural
- Line 288: consist -> consists
- Line 296: insight on -> insight into
- Line 323: composition friendly -> composition-friendly
- Line 360: recognize -> recognise
- Line 379, 396: so called -> so-called
- Line 382: a some -> some
- Line 435: first hand -> first-hand
- Line 511, 528, 532, 543, 547: Junit -> JUnit
- Line 528: emphasize -> emphasise
- Line 529: utilized -> utilised
- Line 541: utilize -> utilise
- Line 559: ehancers -> enhancers

**Comment by Toverklift** [comment]
As far as I'm concerned you can include our chapter in the book 👍

**Review by sandervdo — APPROVED** [review]

**Comment by sandervdo** [comment]
The chapter has been merged! 🎉 
Thank you @joined for the additional comments, much appreciated!

**Pull request merged**
