### PR TITLE
Added team-magento chapter

### PR DESCRIPTION
**Pull request by jghms**
This is our final submission for the chapter on Magento!

### CODE REVIEW

**Review by sandervdo — CHANGES_REQUESTED** [review]
What is the `context-view.xml` for?

As per feedback in your private repository your chapter can be included in the book. You are free to make more improvements before having it merged. Please indicate whether you want to include or exclude your chapter in the book. 😄

**Comment by HansSchouten** [comment]
We would like to have our chapter included in the book. The context-view.xml is the draw.io export file of our context view, this can be ignored.

**Comment by sandervdo** [comment]
@Hansschouten can you remove the file? We want to keep to repo as clean as possible. 😉

**Comment by HansSchouten** [comment]
I have removed the context-view.xml, as well as some other unnecessary file.

**Review by sandervdo — APPROVED** [review]

**Comment by sandervdo** [comment]
Thanks! It has been merged! 😄 🎉

**Pull request merged**
