### PR TITLE
team-beets

### PR DESCRIPTION
**Pull request by bajosoto**
Team Beets chapter

### CODE REVIEW

**Comment by bajosoto** [comment]
Hi @sandervdo, when is the deadline to make the changes? Unfortunately the whole team is unavailable right now to fix some of the observations in our feedback. Others (like the logo. There is no official Beets logo) we just simply can't. If we cannot make it before the deadline, unfortunately we'll have to go with our chapter not being published.

**Comment by sandervdo** [comment]
@bajosoto we want to publish later this week / early next week. Would it be possible to fix the remaining points during the weekend at latest? 😄

**Comment by sandervdo** [comment]
@delftswa2017/team-beets do you still want the chapter to be included? Do you have an ETA for us?

**Comment by sandervdo** [comment]
I'm going to close this PR. In case you still want to make changes and include let us know / re-open this PR. 🙂

**Pull request closed without merging**
