### PR TITLE
Add team Jupyter chapter

### PR DESCRIPTION
**Pull request by joined**
Adding the chapter by team Jupyter!

### CODE REVIEW

**Review by sandervdo — APPROVED** [review]
As per feedback in your private repository your chapter can be included in the book. You are free to make more improvements before having it merged. Please indicate whether you want to include or exclude your chapter in the book. 😄

**Comment by ajayaadhikari** [comment]
Thank you for the feedback. We would like to include our work in the final chapter. We are making small changes now. We will comment again when it's ready.

**Comment by ajayaadhikari** [comment]
@sandervdo We have made our small changes.

**Comment by sandervdo** [comment]
Thanks! 👍 It's merged!

**Pull request merged**
