### PR TITLE
Initialize Contributions Chapter

### PR DESCRIPTION
**Pull request by maxvanzoest**
Added Team Kibana's contributions, please review!

### CODE REVIEW

**Review by sandervdo — COMMENTED** [review]
My idea was to have one common chapter. So not a dedicated section per team. I think it reads better in a style like the introduction (see [README.md](https://github.com/delftswa2017/desosa2017/blob/master/README.md)). Do you agree, or would you prefer a dedicated section per team? 😄 (cc @TimvdLippe: maybe you can share your opinion too?)

**Comment by TimvdLippe** [comment]
I think it would be better to group contributions by type, instead of per team. Then we can quickly list all typo fixes, elaborate on full features/large bug fixes and have a nice story. My 2 cents

**Comment by maxvanzoest** [comment]
I'm fine with both approaches.

**Comment by sandervdo** [comment]
In that case I agree that sorting per type will result in a more coherent story. 👍 Can you make the changes @maxvanzoest? I'll review afterwards. 😄

**Review by sandervdo — CHANGES_REQUESTED** [review]
Please rewrite so that we have sections for the types of contributions.

**Comment by maxvanzoest** [comment]
On it

**Comment by maxvanzoest** [comment]
@sandervdo @TimvdLippe what do you think?

**Review by TimvdLippe — CHANGES_REQUESTED** [review]
I think it would be better to make it a coherent story, instead of a list of pull requests. I don't really have the time now (finishing our chapter), but can probably take a look later this week to also add the contributions of team Yarn. Then we can fiddle around with the structure as a basis for all other contributions

**Comment by maxvanzoest** [comment]
Yeah, that seems like a plan. I think we need all the contributions to be able to make it a coherent story though. Let me know when you have time this week, so we can work things out.

**Comment by sandervdo** [comment]
I will give you write access. That'll be easier. We have enforced admin-reviews anyway. 😄

**Review by sandervdo — APPROVED** [review]
I'll approve this document for now. I'll grant write access to the teams, it'll save a lot of hassle I think.

**Comment by TimvdLippe** [comment]
@sandervdo Then you would need to revert the CONTRIBUTING.md mention? :joy:

**Comment by sandervdo** [comment]
@TimvdLippe yeah, I didn't think it through it seems. 😋 This is easier anyway, last year we did not have the protected branches yet. But now it seems possible to have the setup in an easy and manageable way.

**Pull request merged**
