### PR TITLE
Added team-gradle to the repository!

### PR DESCRIPTION
**Pull request by HugooB**
We've added our final chapter to the DESOSA 2017 repository!

**That's gradlecious!**

### CODE REVIEW

**Review by sandervdo — APPROVED** [review]
As per feedback in your private repository your chapter can be included in the book. You are free to make more improvements before having it merged. Please indicate whether you want to include or exclude your chapter in the book. 😄

**Comment by HugooB** [comment]
I will incorporate the feedback first, afterwards ready to merge! Expect it to be done in a few days..

**Comment by HugooB** [comment]
Made a small change according to the final feedback. The chapter should be ready to merge now! It will be an honor to be in included in the book! :)

**Comment by sandervdo** [comment]
Merged. :tada: Thanks! 👍

**Pull request merged**
