### PR TITLE
Add chapter of team JabRef

### PR DESCRIPTION
**Pull request by TRvanRossum**
Here is the final JabRef chapter.

### CODE REVIEW

**Review by sandervdo — CHANGES_REQUESTED** [review]
Please rename `Book.md` to `chapter.md` as per requirements. 

As per feedback in your private repository your chapter can be included in the book. You are free to make more improvements before having it merged. Please indicate whether you want to include or exclude your chapter in the book. 😄

**Comment by sandervdo** [comment]
I also renamed the top-level folder, I forgot to mention that. For me it's good to merge now. Please let us know whether you want it included or not. 😄

**Review by sandervdo — APPROVED** [review]

**Comment by Asalimianrizi** [comment]
Everything 's good👍.

**Comment by sandervdo** [comment]
Merged. 🎉  Thanks!

**Pull request merged**
