### PR TITLE
Team scikit learn

### PR DESCRIPTION
**Pull request by i-am-xhy**
the chapter contribution for team scikit-learn

### CODE REVIEW

**Review by sandervdo — CHANGES_REQUESTED** [review]
Please create a separate PR for the contributions chapter. Also, please consider the earlier discussions on this (e.g. #3). 😄

**Comment by sandervdo** [comment]
@delftswa2017/team-scikit-learn do you want your chapter to be included or not? Could you please let us know here? Thanks! 😄

**Comment by romikharisnawan** [comment]
Hi @sander2 , I have updated the chapter and would like to include it in chapter as well. Thank you!

**Comment by sandervdo** [comment]
@romikharisnawan the contributions chapter is still in the same pull request (which is causing merge conflicts too). Please remove it from this Pull Request and open a separate Pull Request for the contributions chapter (and also take into account its current format). 😄

**Comment by romikharisnawan** [comment]
I have created PR #44 as the replacement

**Pull request closed without merging**
