### PR TITLE
Two Visual Studio Code contributions

### PR DESCRIPTION
**Pull request by wimspaargaren**
I changed the list of bug fixes to sub paragraphs, since I don't think it's a good idea to add a description of a bug fix in a list. Let me know if this should be changed back.

Furthermore I added two bug fix descriptions, from which the second one(Prefix matching bug) was done in collaboration with @rpjproost .

### CODE REVIEW

**Comment by maxvanzoest** [comment]
Hi @wimspaargaren and @rpjproost, I don't know if you've already seen this: #3.

**Review by sandervdo — CHANGES_REQUESTED** [review]
Thanks for the contributions! Really cool! 👍 

As @maxvanzoest indicates, please also split per PR type. 😄 Then it should be good to go.

**Comment by TimvdLippe** [comment]
I think this PR is superseded by #40 and can be closed.

**Comment by sandervdo** [comment]
@TimvdLippe it will be closed automatically as soon as 96010d0ef84ab657713183e117c58e2e598f391c has been merged into `master`.

**Pull request closed without merging**
