### PR TITLE
Added the final chapter of Team Node

### PR DESCRIPTION
**Pull request by JeroenMandersloot**
This PR contains the final chapter for Team Node!

### CODE REVIEW

**Review by sandervdo — APPROVED** [review]
As per feedback in your private repository your chapter can be included in the book. You are free to make more improvements before having it merged. Please indicate whether you want to include or exclude your chapter in the book. 😄

**Review by sandervdo — CHANGES_REQUESTED** [review]
On a second look; what is the `Context view.xml` file for? Can you clean that up? 😄

**Comment by mr-spd** [comment]
I removed the Context view.xml file. We would like our chapter to be included in the book.

**Review by sandervdo — APPROVED** [review]

**Comment by sandervdo** [comment]
Merged! :tada: Thanks!

**Pull request merged**
